server:
  port: 7575

spring:
  application:
    name: Vilki-Palki
  datasource:
    url: jdbc:postgresql://localhost:5432/avada_sl_j1
    username: avada_sl_j1
    password: PSagTbAFNW
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    username: test.in.odessa@gmail.com
    password: sggcjhmrombnkscg
    port: 587
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
    protocol: smtp

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB